chore: test workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,6 +43,9 @@ jobs:
               with:
                 name: node-modules
 
+            - name: Check if node_modules exists
+              run: test -d node_modules || echo "node_modules directory not found"
+
             - name: Set permissions for node_modules
               run: chmod -R 755 node_modules
 
